# Generated by Django 3.2.24 on 2024-03-03 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
