# Generated by Django 3.2.24 on 2024-03-18 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='name',
        ),
    ]
